### ISSUE TITLE
Replace with (modified) ChatExchange6?

### ISSUE THREAD

**Issue by ByteCommander** [Manishearth/ChatExchange#116]
As @Manishearth suggested, I now rewrote my fork and renamed it **[ChatExchange6](https://github.com/ByteCommander/ChatExchange6)** as `2×3 = 6` and it now supports both Python 2 (Travis-CI successfully tested 2.6) and Python 3 (Travis: 3.4).

I tidied up (==deleted) those old branches and edited some other stuff over time that I am not sure whether you want to lose what you had there or not. Therefore I did not open a pull request but am asking you this way to compare our two versions and decide what you want to merge into your main repository and what not.

**Comment by Manishearth** [comment]
cc @ProgramFOX @Undo1

**Comment by Unihedro** [comment]
the project name "ChatExchange6" (in bold) is mispelt in the original post

**Comment by ByteCommander** [comment]
I'm currently still having issues with 2.6, 3.2, 3.5 and 3.6-dev (nightly) on Travis. I hope I can resolve some of those problems, but I would appreciate if some of you could have a look at the travis outputs and tell me what could be the problem here...

https://travis-ci.org/ByteCommander/ChatExchange6

**Comment by ByteCommander** [comment]
@Unihedro fixed typo in comment.

**Comment by Unihedro** [comment]
Yeah, I noticed.

**Comment by Undo1** [comment]
Does it do anything better or is it just Python-3 compatibility stuff?

**Comment by Unihedro** [comment]
To quote Byte from chat, "It does not do anything new, but lets you do the original stuff now in both Python 2 and 3."

**Comment by ByteCommander** [comment]
@Undo1 Currently it should just be good old ChatExchange but supporting both Python2 and Python3 within the same package. It's mainly ChatExchange reformatted for Python3 plus if-statements added wherever import names are different between 2 and 3, so that always the correct packages is imported.

**Comment by ProgramFOX** [comment]
I fully support a ChatExchange version that works with both Py2 and Py3. :+1:

**Comment by ByteCommander** [comment]
@Manishearth @ProgramFOX  @Undo1 @Unihedro  
I can now proudly announce that CE6 1.0 was successfully released after I was able to fix the testing issues with Python 3.5 and to backport the `logging` module's `Logger.getChild(name)` function for Python 2.6 so that it runs there now too.  
Python 3.6-dev (nightly) is still incompatible with the `coverage` package used for the tests, but I could not find a workaround for that except searching for another testing approach. However, I guess CE6 would run there too.

So what do you think. Should we merge CE6 now? Or have you improvement suggestions before this will happen?

**Comment by Undo1** [comment]
I'm indifferent if it works the same, I don't think we have a pressing need to bring Smokey up to Python 3.x. @ProgramFOX ?

**Comment by ByteCommander** [comment]
@Undo1 It is still Python 2.6 and 2.7 compatible. You don't have to change anything in code that depends on old ChatExchange.

The only thing that changed is the name, but when we decide to merge it, we can name the package back to `chatexchange` without the 6 for compatibility.

**Comment by Undo1** [comment]
Right, but we don't *gain* anything from it is what I'm saying. If we were itching to upgrade to 3.x, it'd be a different story, of course.

**Comment by ByteCommander** [comment]
@Undo1 But it's not only SmokeDetector that is build on CE. There are some more bots and some of them are Python 3, some Python 2. And it's not ideal to manually apply the updates on CE to CE6. Reducing both versions to one project seems the only right step to me.

**Comment by Undo1** [comment]
Oh absolutely, but Smokey is the project I work on. From a strictly selfish point of view, I'm neither for nor against it.

**Comment by ByteCommander** [comment]
So does that mean you want any fancy new stuff included before you vote for a merge? Any proposals? If you want, I will try what I can do...

**Comment by Unihedro** [comment]
Undo's point seems to have missed you completely for some weird reason, so I'll try to put it in another way - This "suggestion" is to add support for CE to run in python3. There's no pressing demand for that and it virtually adds nothing to the project.

**Comment by Undo1** [comment]
What @Unihedro said, but with an amendment at the end: It virtually adds nothing to *my* main project. It adds a lot to CE for those that want to use it with Python 3, but CE isn't really one of my contact projects and I don't have any projects that use Python 3. I'm not in a position to vote on this one way or the other.

**Comment by Unihedro** [comment]
now that the discourse has pretty much finished, no one seems to be against, so consider yourself greenlighted and submit a PR. as long as everything still works and it's only the effort of a click, I'm not sure why you'd get rejected beyond that point

**Comment by ByteCommander** [comment]
@Unihedro It adds Python 3 up to 3.5-dev and also adds downwards compatibility to Python 2.6 which was previously failing as well. And @ProgramFOX and me both need it with Python 3. Others probably to come. 
Also, as there is no argument against it if I rename ChatExchange6 back to ChatExchange, I think we should do this. Thank you for finally agreeing. But I'll wait for @Manishearth 's comment.

**Comment by ProgramFOX** [comment]
So... This is very old already but I thought it's time to dig it up again: no objections have been raised and it would make things easier to have CE6 merged into CE. Poking @Manishearth

**Comment by Manishearth** [comment]
Oh, I have no objection 😄 

Just make a PR?

**Comment by Unihedro** [comment]
fixed by #128
