### ISSUE TITLE
Relicense under dual MIT/Apache 2.0

### ISSUE THREAD

**Issue by Manishearth** [Manishearth/ChatExchange#119]
We currently use the GPL, which is a very restrictive license, and we'd like to change it to something more permissive (in this case, dual licensed under MIT/Apache 2.0). We'll need consent from all contributors to this repository to do so:

 - [x] @Manishearth
 - [x] @jeremybanks 
 - [x] @ProgramFOX 
 - [x] @badp 
 - [x] @hichris1234 
 - [x] @michaelpri10 
 - [x] @ArtOfCode- 
 - [x] @ByteCommander 
 - [x] @FunkyLoveCow 

To agree to relicensing, just leave this comment below or otherwise indicate consent:

```
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.
```

Some more info:

This involves adding the following to the README and including the full text of both licenses in the repository:

```
## License

Licensed under either of

 * Apache License, Version 2.0, ([LICENSE-APACHE](LICENSE-APACHE) or http://www.apache.org/licenses/LICENSE-2.0)
 * MIT license ([LICENSE-MIT](LICENSE-MIT) or http://opensource.org/licenses/MIT)

at your option.

### Contribution

Unless you explicitly state otherwise, any contribution intentionally submitted
for inclusion in the work by you, as defined in the Apache-2.0 license, shall be dual licensed as above, without any
additional terms or conditions.

````

MIT is pretty permissive, so it's preferred by most, however it requires you to include the license in everything using the code. On the other hand, Apache doesn't have this issue, but is incompatible with GPLv2. A dual license gives users the freedom to choose a license of their choice.

Some more rationale can be found in [this](https://github.com/sfackler/rust-openssl/issues/331) similar issue.

**Comment by Undo1** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by ProgramFOX** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by ArtOfCode-** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Manishearth** [comment]
For posterity:

I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by hichris1234** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by FunkyLoveCow** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by badp** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by michaelpri10** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by jeremybanks** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by jeremybanks** [comment]
+1 for the change, too.

**Comment by ByteCommander** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by ByteCommander** [comment]
Actually I don't really care about the license of this project, but what exactly would I have to do to my fork to meet this new thing? Can I get a link to the two licenses, please?

**Comment by Manishearth** [comment]
All the code (aside from typo fixes) in your fork can be relicensed if the authors all agree. Any commits taken from this repo already have agreement so you don't need to re-ask for them.

I'll be opening a pull request shortly, just mimic that :)

**Comment by Manishearth** [comment]
Thanks, all!

**Comment by Manishearth** [comment]
@ByteCommander see #120

**Comment by PeeHaa** [comment]
Thanks for this @Manishearth. And thanks to all contributors. +1

**Comment by ByteCommander** [comment]
@Manishearth Thanks. Well, the only contributor to my fork was me AFAIK... Will update it when I have time, probably on the weekend.
