### ISSUE TITLE
Upload Python3-compatible version to PyPI

### ISSUE THREAD

**Issue by ralphembree** [Manishearth/ChatExchange#132]
Installing chatexchange with pip3 still gives the old version before the merge with chatexchange6.  Could you update PyPI, please?

**Comment by ralphembree** [comment]
Currently, installing my bot requires `--process-dependency-links`, which is both deprecated and unintuitive.  Are there any plans?

**Comment by ralphembree** [comment]
I hate to keep bugging you, but it's been almost three months since I first posted this issue, and I've still seen no action and no response except two upvotes. I've been using ChatExchange6 for a while, but I hate using deprecated features, and I don't like the extra effort required on the part of the people who want to install my program. Despite this, I'm willing to shut up if I'll only get a little feedback. Is this something you don't intend to do? Is it something you'd like to do, but there's something in the way? Is it just something you haven't gotten around to yet? Are there any estimated dates when this might happen?

**Comment by Manishearth** [comment]
Uploaded 0.0.3, sorry about the issues.
