### ISSUE TITLE
Unable to log in properly

### ISSUE THREAD

**Issue by markyi370** [Manishearth/ChatExchange#134]
It appears that a method is being called twice.

Here's a debuggable version of this method:

    @staticmethod
    def user_id_and_name_from_link(link_soup):
        user_name = link_soup.text
        print("link soup " + link_soup['href'].split('/')[-2]);
        user_id = int(link_soup['href'].split('/')[-2])
        return user_id, user_name

And the relevant output from it:

    link soup 242089
    link soup users

What is the problem?

**Comment by Filnor** [comment]
This may be invalidated now, since the old authentication, OpenID, has been replaced.
