### ISSUE TITLE
Update PyPI package to latest version

### ISSUE THREAD

**Issue by quartata** [Manishearth/ChatExchange#143]

**Comment by quartata** [comment]
Would be nice if it could push to PyPI on successful builds

**Comment by ProgramFOX** [comment]
@Manishearth Could you do a PyPI push please? CE is updated to use the new SE logins and bots that depend on the PyPI package (such as SmokeDetector) will get problems if the package isn't there by the 25th...

**Comment by Manishearth** [comment]
Will do soonish.

**Comment by Manishearth** [comment]
https://pypi.org/project/ChatExchange/#history

Done!

**Comment by quartata** [comment]
@ProgramFox Actually we don't use the PyPI version, we have it as a submodule. But thanks though :P

**Comment by quartata** [comment]
@ProgramFox Actually, we don't depend on the PyPI package, we just have it as a Git submodule. but thanks though!

**Comment by ProgramFOX** [comment]
@quartata Oh, okay. I'm very out of the loop about SmokeDetector :P
