### ISSUE TITLE
SE is removing OpenID

### ISSUE THREAD

**Issue by FelixSFD** [Manishearth/ChatExchange#151]
https://meta.stackexchange.com/q/307647/347985

It looks like the library [is using OpenID](https://github.com/Manishearth/ChatExchange/blob/master/chatexchange/browser.py#L145). We need to replace it with the e-mail-based authentication.

If we need help, [Tim Post](https://meta.stackexchange.com/a/307649/347985) is inviting us to contact SE.

**Comment by Manishearth** [comment]
(I'm currently not actively maintaining this library  -- @ByteCommander @ProgramFOX got thoughts?)

**Comment by Manishearth** [comment]
FWIW we use StackExchange's login, which probably won't be going away. The URLs may change though.

**Comment by csnardi** [comment]
We'll need to change a decent amount, since it looks like we directly login through OpenID and then log into a Stack Exchange site. Haven't looked at potential solutions, however.

**Comment by csnardi** [comment]
As an update: looks like stackexchange.com (and thus chat.stackexchange.com) is still using OpenID. Thus, we should probably wait a little bit for that to be changed; otherwise we'll have to maintain two login methods. I have a rough patch to not use OpenID, and I'll take another look whenever SE.com is changed over.

**Comment by jeremyBanks** [comment]
Note [this chat message from Shog](https://chat.stackexchange.com/transcript/message/43253363#43253363):

> expect the stackexchange.com login to go away entirely. Don't use that as a replacement.

I think that the parts of SE.com that require login are being moved into specific sites, and login will be removed. I think logging into chat.SE now will require logging in to a specific site; there won't be any site-agnostic login routes like SE.com currently provides. One issue with this is that when we're logging in to chat.SE, we don't know what sites that user has an account on. It's not possible to determine from the login email.

The least-bad option might be to use `https://stackapps.com/users/login` as the "generic" login route. If the user doesn't already have an profile on the site, we use `/users/openidconfirm` to create it, then `/users/hidecommunities` to minimize this side-effect.

**Comment by Filnor** [comment]
The deadline has been now been moved to August, according to the [monthly DAG team update for June](https://meta.stackexchange.com/a/310868). Nevertheless, we should switch to the new auth or test it if someone has a solution already (@csnardi maybe?).

**Comment by Fortunate-MAN** [comment]
@Filnor For the Java-lib, @FelixSFD implemented a solution in the same lines as @jeremyBanks message. So that solution *should* work, someone just needs to implement it here.

**Comment by Filnor** [comment]
I wrote an implementation that seems to work pretty well, and this is the status of the testing:
- **chat.SO:** All good, no errors
- **chat.SE :** Errored, needs fixes
- **chat.meta.SE:** not tested yet

**Comment by Filnor** [comment]
I rewrote it to work fine on chat.SO and made a fork for that: https://github.com/Filnor/ChatOverflow. I got stuck on the chat.SE login as it appears to still use OpenID and chat.MSE is not working to, but that's probably because it's using another way to login (using return URLS).

**Comment by FelixSFD** [comment]
Tunaki implemented our approach, but it's not published yet: https://github.com/Tunaki/chatexchange/commit/913613fd940733ac3de270694f7898e5cb7b8f6d
