### ISSUE TITLE
make: *** [run-example] Error 1

### ISSUE THREAD

**Issue by raitalharehman** [Manishearth/ChatExchange#154]
error log
>python -W default::Warning examples/chat.py
Traceback (most recent call last):
  File "examples/chat.py", line 80, in <module>
    main(*sys.argv[1:])
TypeError: main() missing 1 required positional argument: 'args'
make: *** [run-example] Error 1

**Comment by raitalharehman** [comment]
What is this? No comment just close issue 

Sent from Mail for Windows 10

**Comment by fortunate-man** [comment]
@raitalharehman If you noticed carefully enough, https://github.com/Manishearth/ChatExchange/commit/0c1e328914b02a90e525d4aa4fdbf106ce16faf9 fixed this issue; Github shows the same:

>  Manishearth closed this in 0c1e328 8 hours ago

**Comment by raitalharehman** [comment]
@fortunate-man thanks
