### ISSUE TITLE
Travis CI migration to travis-ci.com from travis-ci.org

### ISSUE THREAD

**Issue by makyen** [Manishearth/ChatExchange#161]
Travis CI is shutting down travis-ci.org on 2021-06-15 (**in 2 days**). If you continue to desire to use Travis CI for CI testing, then you need to migrate this repository to [travis-ci.com](https://travis-ci.com). See the [documentation for migrating](https://docs.travis-ci.com/user/migrate/open-source-repository-migration#migrating-a-repository).

Note: in order for me to get migration of my repositories to work, it was necessary for me to go to [the main travis-ci.com page](https://travis-ci.com) and re-login/re-auth with GitHub. Prior to doing that, everything *looked like I was signed in* while using travis-ci.com, having gotten there from links either on GitHub or travis-ci.org. However, migration (and updating status from GitHub) didn't actually work (and clicking to migrated wasn't permitted) until I re-logged-in from [the main travis-ci.com page](https://travis-ci.com).

**Comment by Manishearth** [comment]
I think I'd rather just switch to GitHub actions. Happy to merge a PR for that!

**Comment by makyen** [comment]
IMO, moving to GitHub Actions is a good idea. Doing so is the choice we made on our projects. For us, moving away from Travis CI was primarily motivated by [Travis CI changing their pricing structure](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), particularly that they were going to make using Travis [more painful for open source projects](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing#building-on-a-public-repositories-only).<sup>1</sup>

I'll keep in mind that you're looking to move to GitHub Actions. I expect I'll take a stab at doing so, if it's not done by the time I look at it. I don't expect I'll look at it in the near future. What will probably happen is that I'll look at converting to GitHub Actions at the point when I have some other change I want to make to ChatExchange (i.e. I'll likely wait to do the work until it's needed in order to test some other change).

----
1. I can understand Travis implementing changes in an attempt to thwart the abuse they mention in the page linked above. However, that doesn't change the fact that those changes result in, at best, more work on the part of OSS projects in order to use Travis on an ongoing basis, along with uncertainty as to if Travis will permit that use.
