### ISSUE TITLE
Event using

### ISSUE THREAD

**Issue by Peter-developer01** [Manishearth/ChatExchange#175]
How to use the events data? For example:
 1. The user entered a room;
 2. Client generated a chatexchange.events.UserEntered object;
 3. And how to use it? I tried it using as a class instance, as a dict, but this doesn't work.

How to properly use the data from events? Maybe I should try something different?

**Comment by Manishearth** [comment]
It has a `.user` field

**Comment by Peter-developer01** [comment]
But... If this is other events? e.g. `MessageStarred`?

**Comment by Manishearth** [comment]
Check the code for the fields in use. We should probably document this better.
