### ISSUE TITLE
Get current list of users in the room

### ISSUE THREAD

**Issue by Undo1** [Manishearth/ChatExchange#92]
Some applications would benefit from being able to get a list of the users currently in a room. For example, I'd like to be able to do this:

```
>>> charcoal_hq.users 
[<ChatExchange.chatexchange.users.User object at 0x10c8db550>, 
<ChatExchange.chatexchange.users.User object at 0x10c8db710>, 
<ChatExchange.chatexchange.users.User object at 0x10c8db5d0>,
etc.]
```

Can we add this feature?

**Comment by ProgramFOX** [comment]
I've tried to look whether this is possible, and all I have found is that you can [fetch all pingable users in a room](http://chat.meta.stackexchange.com/rooms/pingable/89), but while digging through the chat code, I did not see how chat exactly knows what users are in the room right now.

**Comment by Undo1** [comment]
Sounds like it probably keeps a list somewhere that updates when the web socks says a user has arrived or left, so it'd probably be really hard to do this :(

**Comment by ProgramFOX** [comment]
Aha, I just found something!

When looking at the source of /rooms/89/tavern-of-the-meta, I saw this:
<pre>
CHAT.RoomUsers.initPresent([
        {id: 199700, name: ("J. Steen"), email_hash: ("<hash here>"), reputation: 933, last_post: 1429180589}
        ,{id: 161198, name: ("Bart"), email_hash: ("<hash here>"), reputation: 49248, last_post: 1429180578}
        ,{id: 266345, name: ("SmokeDetector"), email_hash: ("<hash here>"), reputation: 1, last_post: 1429180521}
        ,{id: 166899, name: ("Second Rikudo"), email_hash: ("<hash here>"), reputation: 19794, last_post: 1429180393}
        ,{id: 202832, name: ("Mooseman"), email_hash: ("<hash here>"), reputation: 7463, last_post: 1429179229}
         ... some more people
</pre>
CE could load this when joining a room, and keep track of the users who leave and join using the events.

**Comment by ProgramFOX** [comment]
@Undo1 This now exists: https://github.com/Manishearth/ChatExchange/commit/9b48401f41ad95822cd658fb0ab925ea68481652

@Manishearth Can you close the issue, please?

**Comment by Undo1** [comment]
Sweet! On to updating the blame thing... >:D
